// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class QuizTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void quiz() {
    driver.get("https://normal-frontend.onrender.com/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    driver.findElement(By.cssSelector(".MuiButtonBase-root > img")).click();
    driver.findElement(By.cssSelector(".MuiPaper-root:nth-child(2) > .MuiFormControlLabel-root")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-containedSizeMedium"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiButton-containedSizeMedium")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".MuiPaper-root:nth-child(2) > .MuiFormControlLabel-root")).click();
    driver.findElement(By.cssSelector(".MuiButton-containedSizeMedium")).click();
    driver.findElement(By.cssSelector(".MuiPaper-root:nth-child(3) > .MuiFormControlLabel-root")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-containedSizeMedium"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiButton-containedSizeMedium")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".MuiPaper-root:nth-child(1) > .MuiFormControlLabel-root")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-contained .MuiSvgIcon-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiButton-contained .MuiSvgIcon-root")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".MuiPaper-root:nth-child(1) > .MuiFormControlLabel-root")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-containedSizeMedium"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiButton-containedSizeMedium")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".MuiPaper-root:nth-child(1) > .MuiFormControlLabel-root")).click();
    driver.findElement(By.cssSelector(".MuiButton-containedSizeMedium")).click();
    driver.findElement(By.cssSelector(".MuiPaper-root:nth-child(2) > .MuiFormControlLabel-root")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-containedSizeMedium"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiButton-containedSizeMedium")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".MuiPaper-root:nth-child(3) > .MuiFormControlLabel-root")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-containedSizeMedium"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiButton-containedSizeMedium")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".MuiPaper-root:nth-child(3) > .MuiFormControlLabel-root")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-containedSizeMedium"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiButton-containedSizeMedium")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".MuiPaper-root:nth-child(3) > .MuiFormControlLabel-root")).click();
    driver.findElement(By.cssSelector(".MuiButton-containedSizeMedium")).click();
  }
}
