// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchAndFilterTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchAndFilter() {
    driver.get("https://normal-frontend.onrender.com/");
    driver.manage().window().setSize(new Dimension(1410, 799));
    {
      WebElement element = driver.findElement(By.cssSelector("div:nth-child(2) > .MuiButton-text"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("div:nth-child(2) > .MuiButton-text")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("div:nth-child(3) > .MuiButton-root")).click();
    driver.findElement(By.cssSelector("div:nth-child(5) > .MuiButtonBase-root")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("div:nth-child(8) > .MuiButtonBase-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("div:nth-child(9) > .MuiButtonBase-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".form-control")).click();
    driver.findElement(By.cssSelector(".form-control")).sendKeys("high");
    driver.findElement(By.cssSelector(".form-control")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".form-control")).click();
    driver.findElement(By.cssSelector(".form-control")).sendKeys("high");
    driver.findElement(By.cssSelector(".form-control")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector(".MuiButton-sizeSmall")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("#demo-customized-button > .MuiSvgIcon-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector("#demo-customized-button > .MuiSvgIcon-root")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector("#demo-customized-button > .MuiSvgIcon-root")).click();
    driver.findElement(By.id(":r8:")).click();
    driver.findElement(By.id("site")).click();
    driver.findElement(By.id(":rc1:")).click();
    driver.findElement(By.id(":rc1:")).click();
    {
      WebElement element = driver.findElement(By.id(":rc1:"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id(":rc1:")).click();
    driver.findElement(By.id(":rc1:")).click();
    {
      WebElement element = driver.findElement(By.id(":rc1:"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.id(":rc1:")).click();
    driver.findElement(By.id(":rc1:")).click();
    driver.findElement(By.id(":rc1:")).click();
    driver.findElement(By.id(":rc1:")).click();
    driver.findElement(By.id(":rc1:")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiFormControl-root:nth-child(3) path"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiFormControl-root:nth-child(3) path")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiPickersDay-today"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".MuiPickersDay-today")).click();
    driver.findElement(By.id("site")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".css-ghr9bt"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".css-ghr9bt")).click();
    driver.findElement(By.cssSelector(".MuiButton-sizeSmall")).click();
    driver.findElement(By.cssSelector("#demo-customized-button > .MuiSvgIcon-root")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiFormControl-root:nth-child(2) .MuiButtonBase-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiFormControl-root:nth-child(3) .MuiSvgIcon-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".css-ghr9bt")).click();
    {
      WebElement element = driver.findElement(By.id("add-box-button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    js.executeScript("window.scrollTo(0,152.72727966308594)");
    driver.findElement(By.cssSelector(".form-control")).click();
    driver.findElement(By.cssSelector("div:nth-child(8) > .MuiButtonBase-root")).click();
    driver.findElement(By.id(":rbu:")).click();
    driver.close();
  }
}
