// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SidebarNavigationTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void sidebarNavigation() {
    driver.get("https://normal-frontend.onrender.com/");
    driver.manage().window().setSize(new Dimension(1398, 787));
    driver.findElement(By.cssSelector(".css-1os0gwg path")).click();
    driver.findElement(By.cssSelector(".css-1os0gwg path")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".css-1os0gwg > .MuiSvgIcon-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".css-1os0gwg path")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".css-1os0gwg path"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".MuiListItem-root:nth-child(1) path")).click();
    driver.findElement(By.cssSelector(".MuiListItem-root:nth-child(2) .MuiTypography-root")).click();
    driver.findElement(By.cssSelector(".MuiListItem-root:nth-child(3) .MuiTypography-root")).click();
    driver.findElement(By.cssSelector(".MuiListItem-root:nth-child(4) .MuiTypography-root")).click();
    driver.findElement(By.cssSelector(".MuiListItem-root:nth-child(5) .MuiTypography-root")).click();
    driver.findElement(By.cssSelector(".MuiListItem-root:nth-child(7) .MuiTypography-root")).click();
    driver.findElement(By.cssSelector(".MuiListItem-root:nth-child(1) .MuiTypography-root")).click();
    driver.findElement(By.cssSelector(".MuiListItem-root:nth-child(4)")).click();
    driver.findElement(By.cssSelector(".MuiListItem-root:nth-child(2) .MuiTypography-root")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("div:nth-child(3) > .MuiButton-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.cssSelector("div:nth-child(8) > .MuiButtonBase-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.close();
  }
}
