// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class UpdateProfileTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void updateProfile() {
    driver.get("https://normal-frontend.onrender.com/");
    driver.manage().window().setSize(new Dimension(1398, 787));
    driver.findElement(By.cssSelector(".css-1os0gwg > .MuiSvgIcon-root")).click();
    driver.findElement(By.cssSelector(".MuiListItem-root:nth-child(7)")).click();
    driver.findElement(By.cssSelector("form > div:nth-child(1) > .form-control")).click();
    driver.findElement(By.cssSelector("form > div:nth-child(1) > .form-control")).sendKeys("saumyaSaumyaVaza");
    driver.findElement(By.cssSelector(".row:nth-child(2) > .col:nth-child(1) .form-control")).click();
    driver.findElement(By.cssSelector(".row:nth-child(2) > .col:nth-child(1) .form-control")).sendKeys("saumya");
    driver.findElement(By.id("formLastName")).click();
    driver.findElement(By.id("formLastName")).sendKeys("vasa");
    driver.findElement(By.cssSelector(".row:nth-child(2) > .col:nth-child(2) .form-control")).click();
    driver.findElement(By.cssSelector(".row:nth-child(2) > .col:nth-child(2) .form-control")).sendKeys("20");
    driver.findElement(By.id("formPhone")).click();
    driver.findElement(By.id("formPhone")).sendKeys("6355430888");
    driver.findElement(By.cssSelector(".row:nth-child(2) > .col:nth-child(2) .form-control")).click();
    driver.findElement(By.cssSelector(".row:nth-child(2) > .col:nth-child(2) .form-control")).sendKeys("21");
    driver.findElement(By.cssSelector(".row:nth-child(2) > .col:nth-child(2) .form-control")).click();
    driver.findElement(By.cssSelector(".row:nth-child(2) > .col:nth-child(2) .form-control")).sendKeys("22");
    driver.findElement(By.cssSelector(".row:nth-child(2) > .col:nth-child(2) .form-control")).click();
    driver.findElement(By.cssSelector("div:nth-child(2) > .form-control")).click();
    driver.findElement(By.cssSelector("div:nth-child(2) > .form-control")).sendKeys("science");
    driver.findElement(By.cssSelector("div:nth-child(2) > .btn")).click();
    driver.findElement(By.cssSelector("div:nth-child(2) > .form-control")).sendKeys("world");
    driver.findElement(By.cssSelector("div:nth-child(2) > .btn")).click();
    driver.findElement(By.cssSelector(".btn-primary:nth-child(1)")).click();
    driver.findElement(By.cssSelector("div:nth-child(6) > .btn:nth-child(2)")).click();
    driver.findElement(By.cssSelector(".Mui-focused > .MuiInputBase-input")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiInputBase-root:nth-child(1) path"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".Mui-focused > .MuiInputBase-input")).sendKeys("12345678");
    driver.findElement(By.cssSelector(".MuiInputBase-root:nth-child(1) path")).click();
    driver.findElement(By.cssSelector("path:nth-child(3)")).click();
    driver.findElement(By.cssSelector(".Mui-focused > .MuiInputBase-input")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiInputBase-root:nth-child(2) path"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".Mui-focused > .MuiInputBase-input")).sendKeys("12345678");
    driver.findElement(By.cssSelector(".MuiInputBase-root:nth-child(2) path")).click();
    driver.findElement(By.cssSelector(".Mui-focused > .MuiInputBase-input")).click();
    driver.findElement(By.cssSelector(".Mui-focused > .MuiInputBase-input")).click();
    driver.findElement(By.cssSelector(".Mui-focused > .MuiInputBase-input")).sendKeys("Vasask@3aug");
    driver.findElement(By.cssSelector(".Mui-focused > .MuiInputBase-input")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".css-v9ppqq"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".Mui-focused > .MuiInputBase-input")).sendKeys("Vasask@3aug");
    driver.findElement(By.cssSelector(".css-v9ppqq")).click();
    {
      WebElement element = driver.findElement(By.cssSelector("div:nth-child(9) > .MuiButtonBase-root"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".badge:nth-child(2) path")).click();
    js.executeScript("window.scrollTo(0,225.4545440673828)");
    driver.close();
  }
}
